# Copyright (c) 2022-2023 Pablo González Carrizo
# All rights reserved.

FROM python:3.9.10-slim-bullseye
# turn off buffering to see some output
# (see https://stackoverflow.com/a/57801848/8071370)
ENV PYTHONUNBUFFERED=1
# prevent Python to create pyc files
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /backend
# we need curl for the healthchecks, build-essential to build hnswlib
RUN apt-get update &&\
    apt-get install --no-install-recommends -y curl git build-essential &&\
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /backend/requirements.txt
RUN python3.9 -m pip install -U pip &&\
    python3.9 -m pip install --no-cache-dir -r /backend/requirements.txt

COPY . .

# allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then pip install -e .[dev] ; else pip install . ; fi"
