# Copyright (c) 2022-2023 Pablo González Carrizo
# All rights reserved.

# pyright: reportUndefinedVariable=false, reportGeneralTypeIssues=false

"""add analytics models

Revision ID: 20e43bf62411
Revises: 9f05ae827591
Create Date: 2023-05-03 18:40:21.222251

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "20e43bf62411"
down_revision = "9f05ae827591"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queries",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queries")
    # ### end Alembic commands ###
